## Numpy
NumPy is a general purpose array processing package. It provides a high performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.
### Array
Array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type.

### to install numpy library
pip install numpy
####            or
conda install numpy

In [1]:
## initially we need to import numpy
import numpy as np

In [15]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [3]:
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3, 4, 5])

In [16]:
arr.shape

(5,)

In [11]:
## Multinested array
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,7,6,8,9]
arr1 = np.array([my_lst1,my_lst2,my_lst3])

In [12]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [13]:
arr1.shape

(3, 5)

In [18]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [20]:
arr1.shape

(3, 5)

## Indexing

In [21]:
## Accessing the array elements
arr = np.array([1,2,3,4,5,6,7,8,9])

In [22]:
arr[3]

4

In [24]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [25]:
arr1[1:,3:]

array([[5, 6],
       [8, 9]])

In [26]:
arr1[1,2:]

array([4, 5, 6])

In [30]:
arr2 = np.arange(0,10,step=2)

In [31]:
arr2

array([0, 2, 4, 6, 8])

In [32]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [33]:
## from 2nd index to last index all the value will be replaced by 100
arr2[2:] = 100

In [34]:
arr2

array([  0,   2, 100, 100, 100])

In [35]:
arr3 = arr2

In [36]:
arr3[2:] = 500

In [37]:
arr3

array([  0,   2, 500, 500, 500])

In [38]:
arr2

array([  0,   2, 500, 500, 500])

In [39]:
## array is reference type, so changes in arr3 is reflected to arr2 also
## to avoid this we can use copy function
arr3 = arr2.copy()

In [40]:
arr3[2:] = 1000

In [41]:
arr3

array([   0,    2, 1000, 1000, 1000])

In [42]:
arr2

array([  0,   2, 500, 500, 500])

In [45]:
val = 2
arr3>val

array([False, False,  True,  True,  True])

In [47]:
arr3*2

array([   0,    4, 2000, 2000, 2000])

In [48]:
## to get the element of arrays that are greater than 5
arr3[arr3>5]

array([1000, 1000, 1000])

In [50]:
## create arrays and reshape
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [51]:
## create array of length 4 having all element as 1, default type is float
np.ones(4)

array([1., 1., 1., 1.])

In [52]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [53]:
np.ones((4,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [54]:
## random distribution
np.random.rand(4,2)

array([[0.00488232, 0.07815589],
       [0.60187524, 0.30870996],
       [0.11073501, 0.39509649],
       [0.95234623, 0.38512122]])

In [ ]:
## randn -> select random on the basis of standard normal distribution
arr_ex = np.random.randn(